---
title: "ps_7"
author: "Sabrina Chok"
date: "4/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(janitor)
library(fs)
library(ggthemes)
library(RColorBrewer)
```

```{r data, cache=TRUE, echo=FALSE}

#Download spring 2018 and 2019 Harvard course data from registrar website

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19.xlsx", destfile = "s19.xlsx", mode = "wb")

download.file(url = "https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx", destfile = "s18.xlsx", mode = "wb")

#Read in downloaded excel data files into two separate variables, s19 and s18. 
#Tidy each new dataframe by 1) cleaning variable names for easy reference, 2) skipping unnecessary rows, and 3) filtering out observations without course name data.

s19 <- read_excel("s19.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(! is.na(course_name))
    
s18 <- read_excel("s18.xlsx", skip = 2) %>% 
  clean_names() %>% 
  filter(! is.na(course_name))

#delete files that have been read into variables  

fs::file_delete(c("s19.xlsx", "s18.xlsx"))
```

```{r dataframe, echo=FALSE}
#Prepare dataframe for final graphic which shows greatest course enrollment percent increases and decreases in the Computer Science department.

#Left join spring 2018 and 2019 dataframes by course id to find common classes taught in both semesters. Select columns for course title, name, department, and number of undergrads in 2018 and 2019.

x <- left_join(s18, s19, by = "course_id") %>% 
  select(course_title.x, course_name.x, course_department.x, u_grad.x, u_grad.y) %>% 
  
  #Filter out courses under Computer Science department and have an undergraduate course enrollment of over 15. This is to filter out seminar styled classes as percent changes for small classes are usually quite large.
  
  filter(course_department.x == "Computer Science",
         u_grad.y > 15, 
         u_grad.x > 15) %>% 
  
  #Create change variable which calculates percent change in undergrad enrollment from 2018 to 2019.
  #Create sign variable which notes whether the change variable is positive or negative. This will be useful for using color to differentiate between the values in the final graphic
  
  mutate(change = (u_grad.y - u_grad.x) / u_grad.x * 100, 
         sign = ifelse(change >= 0, "Positive", "Negative"))

#create top5 dataframe by arranging values in change column by highest to lowest and pulling the first five observations 

top5 <- x %>% 
  arrange(desc(change)) %>% 
  slice(1:5)

#create bottom5 dataframe by arranging values in change column by lowest to highest and pulling the first five observations 

bottom5 <- x %>% 
  arrange(change) %>% 
  slice(1:5)

#combine observations in top5 and bottom5 dataframes for the final dataframe for the graphic

y <- bind_rows(top5, bottom5) %>% 
  arrange(desc(change))

```

```{r graphic, echo= FALSE}

#Create graphic that shows trends in Harvard Computer Science Course Enrollment in Spring 2018 to 2019

#Create bar plot with course names on x=axis and percent change in enrollment on y-axis and flipped the axes to make course names more legible. Hide legend because graphic looks more convoluted with it. 

y %>% 
  ggplot(aes(x = reorder(course_name.x, change), y = change, fill = sign)) + geom_col(show.legend = FALSE) + coord_flip() + 
  
  #Add appropriate title, subtitle, and caption to the graphic
  
  labs(title = "Harvard Computer Science Course Enrollment (Spring 2018-19)",
       subtitle = "Classes With Largest Percent Increase and Decrease in Undergraduate Enrollment",
       caption = "Source: Harvard Registrar Course Enrollment Data") +
  
  #Use Wall Street Journal theme with gray background to make the colors of the bars more vibrant
  
  theme_wsj(color = "gray") + scale_fill_brewer(palette = "Set1") +
  
  #Adjust position and size of the title, caption, and subtitle to ensure text fits in the graphic and looks visually appealing
  
  theme(plot.caption = element_text(size = rel(.4)),
        plot.title = element_text(hjust = 1.0, size = 13),
        plot.subtitle = element_text(hjust = 1.0, size = 10)) 
  
```


